[package]
name = "frontend"
build = "build.rs"
version.workspace = true
authors.workspace = true
license-file.workspace = true
edition.workspace = true
readme.workspace = true
repository.workspace = true

[lib]
name = "frontend"
path = "build.rs"

[build-dependencies]
tsync = "2"

