[package]
name = "bob_management"
version = "0.1.0"
default-run = "bob_management"
edition = "2021"
description = "Bob Management GUI"
authors = ["Romanov Simeon ArchArcheoss@proton.me", "Artemev Ilia", "Riadinskii Kirill"]
license = "Unlicense"
repository = "https://github.com/qoollo/bob-management"
publish = false
keywords = [ "BOB", "Management", "GUI" ]
readme = "./README.md"

# Force frontend build
[[bin]]
name = "frontend"
path = "frontend/build.rs"
required-features = [ "frontend" ]

[[bin]]
name = "bob_management"
path = "backend/src/main.rs"
required-features = [ "backend", "frontend" ]

[[bin]]
name = "backend"
path = "backend/src/main.rs"
required-features = [ "backend" ]

[build-dependencies]
# Frontend
tsync = { version = "2", optional = true }

[dependencies]
# Frontend (for `cargo frontend` command)
tsync = { version = "2", optional = true }

# Backend (main.rs)
## Axum related
axum = { version = "0.6", optional = true }
tower = { version = "0.4", optional = true }
tower-http = { version = "0.4", features = ["cors"], optional = true }

## Logging
tracing = { version = "0.1", optional = true }
tracing-subscriber = { version = "0.3", optional = true }

## General
tokio = { version = "1.0", features = [], optional = true }

# CLI
cli = { path = "./cli", optional = true }

# Backend Lib
backend = { path = "./backend", optional = true }

color-eyre = {version = "0.6.2", optional = true }

[workspace]
members = [ "cli", "backend" ]

[features]
default = [ "frontend", "backend", "swagger" ] 
frontend = [ "tsync" ]
swagger = [ "backend/swagger" ]
backend = [ "axum", "tower", "tower-http" , "tracing", "tracing-subscriber", "tokio", "cli", "dep:backend", "color-eyre" ]

[profile.dev]
debug-assertions = true

[profile.release]
# Optimize for size
# opt-level = "s"
# Optimize for speed
opt-level = 3 

# Slightly increase perfomance and reduce binary size
panic = "abort"

[profile.release-lto]
inherits = "release"
# Link Time optimization, causes a bit longer compilation
lto = true
# Maximize size reduction optimization, causes longer compilation
codegen-units = 1 

[profile.min-size]
inherits = "release"
opt-level = "s"
