[alias]
build-backend="build -p bob_management --features backend --features swagger --no-default-features"
build-frontend="build -p frontend --no-default-features" 
run-backend="run --features backend --features swagger --no-default-features"

