[alias]
build-backend="build --features backend swagger --no-default-features"
build-frontend="build -p bob_management --bin frontend --features frontend --no-default-features"
run-backend="run --features backend swagger --no-default-features"

# [build]
# target-dir=".cargo/.build"
