[alias]
backend="build --no-default-features"
frontend="run -p bob_management --bin frontend --features frontend --no-default-features"
swagger="run --features swagger -- --default"

# [build]
# target-dir=".cargo/.build"
