openapi: 3.0.3
info:
  title: bob-management
  description: 'Bob Management GUI: Backend'
  contact:
    name: Romanov Simeon ArchArcheoss@proton.me
  license:
    name: ''
  version: 0.0.0
tags:
- name: bob
  description: BOB management API
