openapi: 3.0.3
info:
  title: bob-management
  description: 'Bob Management GUI: Backend'
  contact:
    name: Romanov Simeon ArchArcheoss@proton.me
  license:
    name: ''
tags:
- name: bob
  description: BOB management API
