name: build-docker

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, labeled, unlabeled]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build alpine image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: dockerfiles/alpine/Dockerfile
          tags: bob-gui:$(date +%s)
