name: update-api-schema

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, labeled, unlabeled]
  push:
    branches: [main]
jobs:
  gen-openapi:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.QOOLLO_BOT_APP_ID }}
          private-key: ${{ secrets.QOOLLO_BOT_PRIVATE_KEY }}
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ steps.app-token.outputs.token }}
          persist-credentials: false
      - uses: actions-rs/cargo@v1
        with:
          command: run
          args: -p utils --bin gen-openapi
      - uses: actions/upload-artifact@v3
        with:
          name: API schemas
          path: api/*
      - name: "Update API schema"
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Autogenerate API"
