name: update-api-schema

on: [push]

jobs:
  gen-openapi:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/cargo@v1
        with:
          command: run
          args: --bin gen-openapi
      - uses: actions/upload-artifact@v3
        with:
          name: API schemas
          path: api/*
      - name: "Update API schema"
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Autogenerate API"
